import { Lato } from "next/font/google";

import { ToastContext } from "./context/ToastContext";
import { AuthContext } from "./context/AuthContext";

import "./globals.css";

const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700"] });

export const metadata = {
  title: "Realtime chat app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthContext>
          <ToastContext />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
